version: "3"

services:
  react-app:
    container_name: react-app
    image: react-app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000